### ISSUE TITLE
S3 Sample Error - Caught exception when uploading file s3://pfifer-connector-test

### ISSUE THREAD

**Issue by OB2B** [awslabs/amazon-kinesis-connectors#92]
Hi,

I'm trying to run the S3-sample and getting the following error.  I've modified the properties file to specify my bucket but it appears to be hard coded to s3://pfifer-connector-test.

Any suggestions on how to correct would be appreciated.

Thanks,

Karen

Oct 20, 2018 1:35:16 PM com.amazonaws.services.kinesis.connectors.s3.S3Emitter emit
SEVERE: **Caught exception when uploading file s3://pfifer-connector-test**/49589361605782634194218334397487174449875603805148545042-49589361605782634194218334421530291150371520080640999442to Amazon S3. Failing this emit attempt.
com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 859C3FD7C229CC32), S3 Extended Request ID: NPaDKs50yl7ptAKZk3Hx2yqaTDfSbcyjn8dq+pgDp4THUXdctW2IVUlDhHsHavhbvnRW1+NC+1I=
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1377)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:923)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:701)
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:453)
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:415)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:364)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3964)
        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1538)
        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1403)
        at com.amazonaws.services.kinesis.connectors.s3.S3Emitter.emit(S3Emitter.java:87)
        at com.amazonaws.services.kinesis.connectors.KinesisConnectorRecordProcessor.emit(KinesisConnectorRecordProcessor.java:162)
        at com.amazonaws.services.kinesis.connectors.KinesisConnectorRecordProcessor.processRecords(KinesisConnectorRecordProcessor.java:136)
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.V1ToV2RecordProcessorAdapter.processRecords(V1ToV2RecordProcessorAdapter.java:42)
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ProcessTask.call(ProcessTask.java:176)
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:49)
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:24)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by tbuckham** [comment]
I've also had the same issue trying to run the test - I've changed the .properties file to point to another S3 bucket, but it still tries to upload to pfifer-connector-test... Any guidance welcome!
Tom

**Comment by fdmsantos** [comment]
You need run  mvn package inside samples folder after change the S3 properties file

**Comment by kmyorgy** [comment]
Belatedly... thanks fdsantos.
